"""add email_verification_locked_until to user

Revision ID: 2ce4a32c0850
Revises: d202fed565c3
Create Date: 2026-08-22 20:04:07.652087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce4a32c0850'
down_revision: Union[str, Sequence[str], None] = 'd202fed565c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verification_locked_until', sa.DateTime(), nullable=True))
    op.alter_column('user', 'email_verification_otp_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_verification_otp_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user', 'email_verification_locked_until')
    # ### end Alembic commands ###
