"""remove todo_exsist column

Revision ID: 36711bca7350
Revises: 8e0645599126
Create Date: 2026-08-19 00:32:52.026177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36711bca7350'
down_revision: Union[str, Sequence[str], None] = '8e0645599126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'todo_exsist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('todo_exsist', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
