"""remove email_verification_token from user

Revision ID: 7278df16ff99
Revises: 36711bca7350
Create Date: 2026-08-19 22:43:09.213127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7278df16ff99'
down_revision: Union[str, Sequence[str], None] = '36711bca7350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email_verification_token'), 'user', type_='unique')
    op.drop_column('user', 'otp')
    op.drop_column('user', 'email_verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_user_email_verification_token'), 'user', ['email_verification_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
