from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7379627cd940'
down_revision: Union[str, Sequence[str], None] = '86e6556a5aca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'user',
        sa.Column(
            'email_verification_token',
            sa.String(length=255),
            nullable=True
        )
    )

    op.add_column(
        'user',
        sa.Column(
            'email_verified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.create_unique_constraint(
        'uq_user_email_verification_token',
        'user',
        ['email_verification_token']
    )


def downgrade() -> None:
    op.drop_constraint(
        'uq_user_email_verification_token',
        'user',
        type_='unique'
    )

    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'email_verification_token')




# """add email verification fields

# Revision ID: 7379627cd940
# Revises: 86e6556a5aca
# Create Date: 2026-08-16 22:48:31.307756

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# import sqlmodel

# # revision identifiers, used by Alembic.
# revision: str = '7379627cd940'
# down_revision: Union[str, Sequence[str], None] = '86e6556a5aca'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('user', sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
#     op.add_column('user', sa.Column('email_verified', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
#     op.create_unique_constraint(None, 'user', ['email_verification_token'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'user', type_='unique')
#     op.drop_column('user', 'email_verified')
#     op.drop_column('user', 'email_verification_token')
#     # ### end Alembic commands ###
