"""remove todo_exsist column

Revision ID: 8e0645599126
Revises: fe2092024ad9
Create Date: 2026-08-19 00:16:21.047848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0645599126'
down_revision: Union[str, Sequence[str], None] = 'fe2092024ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'todo_exsist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'todo_exsist',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
