"""add password reset columns

Revision ID: cbe519f251c7
Revises: b7e23db05501
Create Date: 2026-08-30 16:19:52.432130

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe519f251c7'
down_revision: Union[str, Sequence[str], None] = 'b7e23db05501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('password_reset_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_token_expires_at')
    op.drop_column('user', 'password_reset_token_hash')
    # ### end Alembic commands ###
 